source 'https://github.com/CocoaPods/Specs.git'

target 'FRKTextEntryViewController', :exclusive => true do
  pod "FRKTextEntryViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FRKTextEntryViewController", :path => "../"

  
end
